/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb4ab",
        "on-surface-variant": "#5a413d",
        "tertiary-fixed": "#e7e4b9",
        "on-tertiary-fixed-variant": "#494828",
        "outline": "#8e706c",
        "on-error": "#ffffff",
        "surface-tint": "#b22a1e",
        "tertiary": "#61603e",
        "primary-fixed-dim": "#ffb4a9",
        "tertiary-container": "#afad85",
        "secondary-fixed": "#ffdad6",
        "error-container": "#ffdad6",
        "secondary": "#bb0013",
        "background": "#f9f9f9",
        "inverse-primary": "#ffb4a9",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-container": "#ffafa3",
        "surface-dim": "#dadada",
        "on-background": "#1b1b1b",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#1d1d03",
        "on-primary-fixed": "#410000",
        "outline-variant": "#e2beb9",
        "surface-variant": "#e2e2e2",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#424122",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f9",
        "primary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#cbc89f",
        "on-secondary-fixed": "#410002",
        "surface-container": "#eeeeee",
        "secondary-container": "#e9061c",
        "on-surface": "#1b1b1b",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "primary-container": "#9e1b12",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#93000c",
        "surface-container-low": "#f3f3f3",
        "on-primary-fixed-variant": "#900e09",
        "primary": "#7a0001",
        "surface-container-highest": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
      },
      spacing: {
        "margin-mobile": "20px",
        "base-unit": "8px",
        "section-padding": "80px",
        "gutter": "24px",
        "container-max-width": "1200px",
      },
      fontFamily: {
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Epilogue", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
